// DefaultQuizzes.js
export const defaultQuizzes = [
  {
    id: "static-1",
    title: "Introduction to Computers",
    description: "Basic concepts in computing and hardware fundamentals.",
    difficulty: "Easy",
    duration: 20,
    icon: "Cpu",
    bgColor: "#4ade80",
    owner: "static",
    questions: [
      { question: "What is a computer?", options: ["A machine", "A fruit"], answer: 0 },
      { question: "Which is an input device?", options: ["Mouse", "Monitor"], answer: 0 },
      { question: "Which is an output device?", options: ["Keyboard", "Printer"], answer: 1 },
      { question: "CPU stands for?", options: ["Central Processing Unit", "Central Power Unit"], answer: 0 },
      { question: "RAM is used for?", options: ["Permanent storage", "Temporary memory"], answer: 1 },
    ],
  },
  {
    id: "static-2",
    title: "Networking Basics",
    description: "Covers IP addresses, routers, and data transmission.",
    difficulty: "Medium",
    duration: 30,
    icon: "Wifi",
    bgColor: "#60a5fa",
    owner: "static",
    questions: [
      { question: "What does LAN stand for?", options: ["Local Area Network", "Large Area Net"], answer: 0 },
      { question: "IP address is used for?", options: ["Identify devices", "Control power"], answer: 0 },
      { question: "Router function?", options: ["Connect networks", "Store data"], answer: 0 },
      { question: "WAN stands for?", options: ["Wide Area Network", "Wireless Access Network"], answer: 0 },
      { question: "Which protocol is used for web?", options: ["HTTP", "FTP"], answer: 0 },
    ],
  },
  {
    id: "static-3",
    title: "Programming Fundamentals",
    description: "Variables, data types, and basic logic.",
    difficulty: "Easy",
    duration: 25,
    icon: "Code",
    bgColor: "#facc15",
    owner: "static",
    questions: [
      { question: "What is a variable?", options: ["Storage", "Food"], answer: 0 },
      { question: "Data type for numbers?", options: ["String", "Integer"], answer: 1 },
      { question: "Boolean can be?", options: ["True/False", "Yes/No"], answer: 0 },
      { question: "Loop used for repeating?", options: ["for", "if"], answer: 0 },
      { question: "Function is used to?", options: ["Store code", "Run multiple times"], answer: 0 },
    ],
  },
  {
    id: "static-4",
    title: "Databases 101",
    description: "Learn about tables, queries, and basic SQL.",
    difficulty: "Medium",
    duration: 35,
    icon: "Database",
    bgColor: "#f87171",
    owner: "static",
    questions: [
      { question: "What is SQL used for?", options: ["Design", "Data Management"], answer: 1 },
      { question: "Primary key is?", options: ["Unique identifier", "Data type"], answer: 0 },
      { question: "Foreign key is?", options: ["Reference to other table", "Same table ID"], answer: 0 },
      { question: "Table row is called?", options: ["Record", "Column"], answer: 0 },
      { question: "Table column is called?", options: ["Field", "Entry"], answer: 0 },
    ],
  },
  {
    id: "static-5",
    title: "Cloud Computing",
    description: "Introduction to cloud services and storage.",
    difficulty: "Medium",
    duration: 40,
    icon: "Cloud",
    bgColor: "#a78bfa",
    owner: "static",
    questions: [
      { question: "Which is a cloud provider?", options: ["AWS", "Dell"], answer: 0 },
      { question: "SaaS stands for?", options: ["Software as a Service", "Storage as a Service"], answer: 0 },
      { question: "IaaS stands for?", options: ["Infrastructure as a Service", "Internet as a Service"], answer: 0 },
      { question: "Cloud storage example?", options: ["Google Drive", "USB"], answer: 0 },
      { question: "Private cloud is?", options: ["Internal usage", "Public usage"], answer: 0 },
    ],
  }
];
